create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  phone text default '',
  password_hash text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text not null,
  category text not null,
  level text not null,
  price numeric(10, 2) not null default 0 check (price >= 0),
  likes_count integer not null default 0 check (likes_count >= 0),
  order_index integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint not null unique references public.courses(id) on delete cascade,
  title text not null,
  theory text not null default '',
  pre_code text not null default '',
  task text not null default '',
  required_steps text not null default '[]',
  download_content text not null default '',
  quiz_question text not null default '',
  quiz_options text not null default '[]',
  quiz_answer_index integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, course_id)
);

create table if not exists public.course_likes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, course_id)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists lessons_set_updated_at on public.lessons;

create trigger lessons_set_updated_at
before update on public.lessons
for each row
execute function public.set_updated_at();

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter default privileges in schema public
grant select, insert, update, delete on tables to anon, authenticated;

alter default privileges in schema public
grant usage, select on sequences to anon, authenticated;
